---
site_name: "MkDocs Ansible Collection"
site_url: "https://mkdocs-ansible-collection.readthedocs.io/en/latest/"
repo_url: "https://github.com/cmsirbu/mkdocs-ansible-collection"

theme:
  name: "material"
  navigation_depth: 4
  features:
    - "content.action.edit"
    - "content.action.view"
    - "content.code.copy"
    - "navigation.footer"
    - "navigation.indexes"
    - "navigation.tabs"
    - "navigation.tabs.sticky"
    - "navigation.tracking"
    - "search.highlight"
    - "search.share"
    - "search.suggest"
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: "default"
      primary: "orange"
      accent: "deep orange"
      toggle:
        icon: "material/weather-sunny"
        name: "Switch to dark mode"

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: "slate"
      primary: "orange"
      accent: "deep orange"
      toggle:
        icon: "material/weather-night"
        name: "Switch to light mode"

plugins:
  - "search"
  - "ansible-collection":
      "collections":
        - "ansible.builtin"
        - "ansible.posix"

markdown_extensions:
  - "admonition"
  - "toc":
      permalink: true
  - "attr_list"
  - "md_in_html"
  - "pymdownx.highlight":
      anchor_linenums: true
  - "pymdownx.inlinehilite"
  - "pymdownx.snippets"
  - "pymdownx.superfences":
      custom_fences:
        - name: "mermaid"
          class: "mermaid"
          format: !!python/name:pymdownx.superfences.fence_code_format
  - "footnotes"

watch:
  - "README.md"

nav:
  - "index.md"
